#!/usr/bin/env bash
set -euo pipefail

# Build script for Linux.
# Usage: ./build_exe_linux.sh

root="$(cd "$(dirname "$0")" && pwd)"
cd "$root"

# Generate build info (same format as Windows: yyMMddHHmm)
build_py="$root/src/sgm/_build.py"
build_num=$(date +"%y%m%d%H%M")
git_sha=$(git rev-parse --short HEAD 2>/dev/null || echo "")

cat > "$build_py" << EOF
# Auto-generated by build_exe_linux.sh
BUILD = '$build_num'
GIT_SHA = '$git_sha'
EOF

echo "Generated $build_py (BUILD=$build_num, GIT_SHA=$git_sha)"

# Prefer venv python if available
if [ -x "$root/.venv/bin/python" ]; then
  python="$root/.venv/bin/python"
else
  if command -v python3 >/dev/null 2>&1; then
    python="$(command -v python3)"
  else
    python="$(command -v python)"
  fi
fi

echo "Using python: $python"

# Ensure PyInstaller is available
if ! "$python" -m pip show pyinstaller >/dev/null 2>&1; then
  echo "PyInstaller not found in environment; installing..."
  "$python" -m pip install --upgrade pyinstaller
fi

# Clean prior outputs
rm -rf "$root/dist" "$root/build"

# Note: PyInstaller --icon is not supported on Linux (only Windows/macOS)

# PyInstaller add-data separator on Linux (POSIX) is ':'
addData="resources:resources"

echo "Running PyInstaller..."

"$python" -m PyInstaller \
  --noconfirm \
  --clean \
  --onefile \
  --name "SprintGameManager" \
  --paths "src" \
  --add-data "$addData" \
  "main.py"

echo "Built: $root/dist/SprintGameManager"
