#!/usr/bin/env bash
set -euo pipefail

# Build script for Linux.
# Usage: ./build_exe_linux.sh

root="$(cd "$(dirname "$0")" && pwd)"
cd "$root"

# Generate build info (same format as Windows: yyMMddHHmm)
build_py="$root/src/sgm/_build.py"
build_num=$(date +"%y%m%d%H%M")
git_sha=$(git rev-parse --short HEAD 2>/dev/null || echo "")

cat > "$build_py" << EOF
# Auto-generated by build_exe_linux.sh
BUILD = '$build_num'
GIT_SHA = '$git_sha'
EOF

echo "Generated $build_py (BUILD=$build_num, GIT_SHA=$git_sha)"

# Require a virtual environment to avoid PEP 668 issues on modern distros.
venv_dir="$root/.venv"

if [ ! -x "$venv_dir/bin/python" ]; then
  echo "Virtual environment not found at $venv_dir"
  echo "Creating one now..."
  python3 -m venv "$venv_dir"
  echo "Installing dependencies..."
  "$venv_dir/bin/pip" install --upgrade pip
  "$venv_dir/bin/pip" install -r "$root/requirements.txt"
  "$venv_dir/bin/pip" install -r "$root/requirements-build.txt"
fi

python="$venv_dir/bin/python"
echo "Using python: $python"

# Ensure PyInstaller is available
if ! "$python" -m pip show pyinstaller >/dev/null 2>&1; then
  echo "PyInstaller not found in venv; installing..."
  "$python" -m pip install --upgrade pyinstaller
fi

# Clean prior outputs
rm -rf "$root/dist" "$root/build"

# Note: PyInstaller --icon is not supported on Linux (only Windows/macOS)

# PyInstaller add-data separator on Linux (POSIX) is ':'
addData="resources:resources"

echo "Running PyInstaller..."

"$python" -m PyInstaller \
  --noconfirm \
  --clean \
  --onefile \
  --name "SprintGameManager" \
  --paths "src" \
  --add-data "$addData" \
  "main.py"

echo "Built: $root/dist/SprintGameManager"
